# Generated by Django 4.2.14 on 2025-08-17 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardtable',
            options={'ordering': ['-total_points', 'rank']},
        ),
        migrations.AddField(
            model_name='leaderboardtable',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='leaderboardtable',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='leaderboardtable',
            unique_together={('user', 'category')},
        ),
    ]
