# Generated by Django 4.2.14 on 2025-09-03 00:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', tinymce.models.HTMLField()),
                ('category', models.CharField(choices=[('application', 'Application'), ('benefits', 'Benefits'), ('growth', 'Growth'), ('popular', 'Popular'), ('general', 'General')], default='general', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduateProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('duration_months', models.IntegerField(default=12)),
                ('program_type', models.CharField(choices=[('cybersecurity', 'Cybersecurity'), ('software_engineering', 'Software Engineering'), ('data_science', 'Data Science'), ('ai_ml', 'AI & Machine Learning'), ('general', 'General Technology')], max_length=50)),
                ('start_date', models.DateField()),
                ('application_deadline', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overview', tinymce.models.HTMLField()),
                ('curriculum', tinymce.models.HTMLField()),
                ('benefits', tinymce.models.HTMLField()),
                ('requirements', tinymce.models.HTMLField()),
                ('application_process', tinymce.models.HTMLField()),
            ],
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_notification', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('lead', 'Lead'), ('intern', 'Internship')], default='entry', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract'), ('internship', 'Internship')], max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(choices=[('Remote', 'Remote'), ('OnSite', 'OnSite'), ('Hybrid', 'Hybrid')], max_length=100),
        ),
    ]
