# Generated by Django 4.2.14 on 2025-05-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='upskilling_progress',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
