# Generated by Django 4.2.14 on 2025-09-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
