# Generated by Django 4.2.14 on 2025-09-19 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='vault/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('teams', 'Selected teams')], default='private', max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_teams', models.ManyToManyField(blank=True, to='auth.group')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vault_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
