# Generated by Django 4.2.14 on 2025-09-14 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_student_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vaultdocument',
            name='allowed_teams',
        ),
        migrations.AddField(
            model_name='vaultdocument',
            name='allowed_projects',
            field=models.ManyToManyField(blank=True, related_name='vault_documents', to='home.project'),
        ),
        migrations.AlterField(
            model_name='vaultdocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('projects', 'Selected projects'), ('private', 'Private (uploader only)')], default='public', max_length=16),
        ),
    ]
