# Generated by Django 4.2.14 on 2025-08-18 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adninsesssion_knowndevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connect_with_me',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='connect with me'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_information',
            field=models.TextField(blank=True, null=True, verbose_name='contact information'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='knowndevice',
            name='last_seen',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
