# Generated by Django 4.2.14 on 2025-08-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('home', '0002_vaultdocument_adninsesssion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultdocument',
            name='allowed_teams',
            field=models.ManyToManyField(blank=True, related_name='vault_documents', to='auth.group'),
        ),
        migrations.AddField(
            model_name='vaultdocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('teams', 'Selected teams'), ('private', 'Private (uploader only)')], default='public', max_length=16),
        ),
    ]
