# Generated by Django 4.2.14 on 2025-09-07 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipRotationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lock', models.CharField(default='default', max_length=16, unique=True)),
                ('last_index', models.IntegerField(default=-1)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
