# Generated by Django 4.2.14 on 2025-09-09 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_teammember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='image_url',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='linkedin_url',
        ),
        migrations.AddField(
            model_name='teammember',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
