# Generated by Django 4.1.12 on 2023-12-10 05:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_alter_user_unique_together_alter_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='course title')),
                ('code', models.CharField(blank=True, max_length=150, verbose_name='course code')),
                ('is_postgraduate', models.BooleanField(default=False, verbose_name='postgraduate status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='trimester',
            field=models.CharField(blank=True, choices=[('T1', 'Trimester 1'), ('T2', 'Trimester 2'), ('T3', 'Trimester 3')], max_length=10, verbose_name='trimester'),
        ),
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.CharField(blank=True, choices=[('SIT782', 'SIT782'), ('SIT764', 'SIT764')], max_length=50, verbose_name='unit'),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.PositiveIntegerField(blank=True, default=2023),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='course', to='home.course'),
        ),
    ]
