# Generated by Django 4.2.14 on 2025-09-13 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userdeletionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdeletionrequest',
            name='executed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
