# Generated by Django 4.2.14 on 2025-09-16 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_userscore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
    ]
