# Generated by Django 4.1.12 on 2024-04-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_course_rename_user_id_student_user_student_trimester_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=200)),
                ("message", models.TextField()),
            ],
        ),
    ]
