# Generated by Django 4.2.14 on 2025-09-14 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_recognizeddevice_userdevice_delete_knowndevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device_fingerprint',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='user_agent',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RecognizedDevice',
        ),
    ]
