# Generated by Django 5.0.4 on 2024-04-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_message'),
        ('home', '0005_alter_contact_message_article'),
    ]

    operations = [
    ]
