# Generated by Django 4.1.12 on 2024-04-14 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contact_message'),
        ('home', '0005_alter_contact_message_article'),
    ]

    operations = [
    ]
