# Generated by Django 4.1.12 on 2024-04-16 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_skill_progress'),
        ('home', '0006_merge_20240415_0229'),
    ]

    operations = [
    ]
