# Generated by Django 5.0.4 on 2024-04-21 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_upskill'),
        ('home', '0006_merge_20240415_0229'),
    ]

    operations = [
    ]
