# Generated by Django 4.1.12 on 2024-04-23 03:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0006_merge_20240420_2230"),
        ("home", "0008_contact_central"),
    ]

    operations = []
