# Generated by Django 5.0.4 on 2024-04-22 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20240420_2230'),
        ('home', '0007_merge_0004_upskill_0006_merge_20240415_0229'),
        ('home', '0008_contact_central'),
    ]

    operations = [
    ]
