# Generated by Django 5.0.4 on 2024-04-22 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_20240422_1905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Upskill',
        ),
    ]
