# Generated by Django 4.1.12 on 2024-04-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_merge_0006_merge_20240420_2230_0008_contact_central'),
    ]

    operations = [
        migrations.CreateModel(
            name='Smishingdetection_join_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
    ]
