# Generated by Django 4.1.12 on 2024-04-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_otptoken'),
        ('home', '0010_smishingdetection_join_us'),
    ]

    operations = [
    ]
