# Generated by Django 4.1.12 on 2024-05-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_module_studentmoduleprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='skill',
        ),
        migrations.AddField(
            model_name='progress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='skill',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='home.module'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(through='home.Progress', to='home.skill'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='progress',
            unique_together={('student', 'skill')},
        ),
        migrations.DeleteModel(
            name='StudentModuleProgress',
        ),
    ]
