# Generated by Django 4.1.12 on 2024-05-03 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_merge_0010_otptoken_0010_smishingdetection_join_us'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact_central',
        ),
        migrations.AlterField(
            model_name='student',
            name='unit',
            field=models.CharField(blank=True, choices=[('SIT782', 'SIT782'), ('SIT764', 'SIT764'), ('SIT378', 'SIT378'), ('SIT374', 'SIT374')], max_length=50, verbose_name='unit'),
        ),
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
