# Generated by Django 5.0.4 on 2024-05-12 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_upskill'),
        ('home', '0012_delete_contact_central_alter_student_unit_and_more'),
    ]

    operations = [
    ]
