# Generated by Django 4.2.7 on 2024-05-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_contact_central_alter_student_unit_and_more'),
        ('home', '0014_skill_slug'),
    ]

    operations = [
    ]
