# Generated by Django 4.2.7 on 2024-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20240508_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects_join_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('message', models.TextField(max_length=1000)),
                ('page_name', models.CharField(max_length=100)),
            ],
        ),
    ]
