# Generated by Django 5.0.4 on 2024-05-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_webpage_id_alter_webpage_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
