# Generated by Django 4.2.7 on 2024-05-12 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_merge_20240508_2315'),
        ('home', '0016_alter_webpage_url'),
    ]

    operations = [
    ]
