# Generated by Django 5.0.4 on 2024-05-19 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_ddt_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ddt_contact',
            options={'verbose_name': 'DDT_contact', 'verbose_name_plural': 'DDT_contact'},
        ),
    ]
