# Generated by Django 5.0.4 on 2024-05-19 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_ddt_contact_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='updated_at',
        ),
    ]
