# Generated by Django 4.2.7 on 2024-05-21 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_projects_join_us'),
        ('home', '0020_remove_webpage_created_at_remove_webpage_is_active_and_more'),
    ]

    operations = [
    ]
