# Generated by Django 4.1.12 on 2024-09-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_merge_20240522_0413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, choices=[('BDS', 'Bachelor of Data Science'), ('BCS', 'Bachelor of Computer Science'), ('BCYB', 'Bachelor of Cyber Security'), ('BIT', 'Bachelor of Information Technology'), ('BSE', 'Bachelor of Software Enginerring'), ('BAI', 'Bachelor of AI'), ('MAAI', 'Master of Applied AI'), ('MDS', 'Master of Data Science'), ('MIT', 'Master of Information Technology'), ('MITM', 'Master of IT Management'), ('MCS', 'Master of Cyber Security')], max_length=10, null=True),
        ),
    ]
