# Generated by Django 4.1.12 on 2024-09-12 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_student_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code',
            field=models.CharField(choices=[('proj1', 'Project 1'), ('proj2', 'Project 2'), ('proj3', 'Project 3'), ('proj4', 'Project 4')], default='DEFAULT_CODE', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='p1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p1_preferences', to='home.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='p2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p2_preferences', to='home.project'),
        ),
        migrations.AlterField(
            model_name='student',
            name='p3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='p3_preferences', to='home.project'),
        ),
    ]
