# Generated by Django 4.2.7 on 2024-08-19 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='project',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_by',
        ),
    ]
