# Generated by Django 4.1.12 on 2024-09-15 07:52

from django.db import migrations, models

def add_projects(apps, schema_editor):
    Project = apps.get_model('home', 'Project')
    project_titles = [
        "AppAttack",
        "Malware",
        "PT-GUI",
        "Smishing Detection",
        "Deakin CyberSafe VR",
        "Deakin Threat Mirror"
    ]
    for title in project_titles:
        Project.objects.create(title=title)


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_project_code_alter_student_p1_alter_student_p2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='code',
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(choices=[('AppAttack', 'AppAttack'), ('Malware', 'Malware'), ('PT-GUI', 'PT-GUI'), ('Smishing_Detection', 'Smishing Detection'), ('Deakin_CyberSafe_VR', 'Deakin CyberSafe VR'), ('Deakin_Threat_Mirror', 'Deakin Threat Mirror')], max_length=150, verbose_name='project title'),
        ),
    ]
