# Generated by Django 4.2.7 on 2024-09-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cyberchallenge_userchallenge'),
        ('home', '0023_profile_bio'),
    ]

    operations = [
    ]
