# Generated by Django 5.0.4 on 2024-09-18 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cyberchallenge_userchallenge'),
        ('home', '0023_profile_bio'),
    ]

    operations = [
    ]
