# Generated by Django 4.2.14 on 2024-09-19 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cyberchallenge_userchallenge'),
        ('home', '0023_profile_bio'),
    ]

    operations = [
    ]
