# Generated by Django 4.2.14 on 2024-09-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_merge_20240919_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='userchallenge',
            name='user',
        ),
        migrations.DeleteModel(
            name='CyberChallenge',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserChallenge',
        ),
    ]
