# Generated by Django 4.2.14 on 2024-11-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cyberchallenge_userchallenge'),
        ('home', '0022_feedback'),
        ('home', '0023_profile_bio'),
        ('home', '0024_remove_project_code_alter_project_title'),
    ]

    operations = [
    ]
