# Generated by Django 5.0.4 on 2024-09-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_feedback'),
        ('home', '0023_project_code_alter_student_p1_alter_student_p2_and_more'),
        ('home', '0024_merge_20240918_1139'),
    ]

    operations = [
    ]
