# Generated by Django 4.2.14 on 2024-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_merge_20241118_2313"),
    ]

    operations = [
        
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                choices=[
                    ("AppAttack", "AppAttack"),
                    ("Malware", "Malware"),
                    ("PT-GUI", "PT-GUI"),
                    ("Smishing_Detection", "Smishing Detection"),
                    ("Deakin_CyberSafe_VR", "Deakin CyberSafe VR"),
                    ("Deakin_Threat_Mirror", "Deakin Threat Mirror"),
                    ("Company_Website_Development", "Company Website Development"),
                ],
                max_length=150,
                verbose_name="project title",
            ),
        ),
    ]
