# Generated by Django 4.2.7 on 2024-09-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_document_description_alter_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='media\\documents'),
        ),
    ]
