# Generated by Django 4.1.12 on 2024-09-21 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0025_merge_20240921_1014"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("isActive", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="userchallenge",
            name="page_name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="feedback",
            name="feedback_type",
            field=models.CharField(
                choices=[
                    ("general", "General Inquiry"),
                    ("bug", "Bug Report"),
                    ("improvement", "Improvement Suggestion"),
                    ("feature", "Request for a Feature"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title",
            field=models.CharField(
                choices=[
                    ("AppAttack", "AppAttack"),
                    ("Malware", "Malware"),
                    ("PT-GUI", "PT-GUI"),
                    ("Smishing_Detection", "Smishing Detection"),
                    ("Deakin_CyberSafe_VR", "Deakin CyberSafe VR"),
                    ("Deakin_Threat_Mirror", "Deakin Threat Mirror"),
                    ("Company_Website_Development", "Company Website Development"),
                ],
                max_length=150,
                verbose_name="project title",
            ),
        ),
    ]
