# Generated by Django 4.2.14 on 2024-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0026_blogpost_alter_feedback_feedback_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
