# Generated by Django 4.2.7 on 2024-09-19 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cyberchallenge_userchallenge'),
        ('home', '0023_profile_bio'),
        ('home', '0026_alter_document_file'),
    ]

    operations = [
    ]
