# Generated by Django 4.2.14 on 2024-11-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20241119_1946'),
        ('home', '0026_announcement_blogpost_alter_feedback_feedback_type_and_more'),
    ]

    operations = [
    ]
