# Generated by Django 4.2.14 on 2024-12-03 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0027_contactsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactsubmission",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
