# Generated by Django 4.2.14 on 2024-11-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_securityevent'),
        ('home', '0027_merge_20241123_0110'),
        ('home', '0027_merge_20241123_0914'),
    ]

    operations = [
    ]
