# Generated by Django 4.2.7 on 2024-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_merge_20241124_0718'),
        ('home', '0028_merge_20241125_1334'),
    ]

    operations = [
    ]
