# Generated by Django 4.2.14 on 2024-11-27 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20241117_2315'),
        ('home', '0028_merge_20241125_1334'),
    ]

    operations = [
    ]
