# Generated by Django 4.2.14 on 2024-11-29 10:29

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_merge_20241125_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', tinymce.models.HTMLField()),
                ('location', models.CharField(choices=[('Remote', 'Remote'), ('OnSite', 'OnSite')], max_length=100)),
                ('job_type', models.CharField(choices=[('FT', 'Full-time'), ('PT', 'Part-time'), ('CT', 'Contract')], max_length=50)),
                ('posted_date', models.DateField(auto_now_add=True)),
                ('closing_date', models.DateField()),
            ],
        ),
    ]
