# Generated by Django 4.2.14 on 2024-11-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_merge_20241122_1530'),
        ('home', '0028_merge_20241125_1334'),
    ]

    operations = [
    ]
