# Generated by Django 4.2.14 on 2024-12-01 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_experience_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
