# Generated by Django 4.2.14 on 2024-12-05 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_apimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='apimodel',
            name='field_name',
            field=models.CharField(default='Default Value', max_length=255),
        ),
    ]
