# Generated by Django 4.2.14 on 2024-12-03 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_contact_email'),
        ('home', '0030_jobapplication'),
    ]

    operations = [
    ]
