# Generated by Django 4.2.14 on 2024-11-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_examplemodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examplemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
