# Generated by Django 4.2.14 on 2024-12-07 16:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0026_blogpost_alter_feedback_feedback_type_and_more"),
        ("home", "0031_merge_0030_alter_contact_email_0030_jobapplication"),
    ]

    operations = []
