# Generated by Django 4.2.14 on 2024-12-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20241119_1655'),
        ('home', '0030_delete_feedback'),
        ('home', '0031_merge_0030_alter_contact_email_0030_jobapplication'),
    ]

    operations = [
    ]
