# Generated by Django 4.2.14 on 2024-12-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20241207_1845'),
        ('home', '0033_leaderboardtable_category'),
    ]

    operations = [
    ]
