# Generated by Django 4.2.14 on 2024-12-08 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_merge_20241127_1618'),
        ('home', '0034_merge_20241208_1620'),
    ]

    operations = [
    ]
