# Generated by Django 4.2.14 on 2024-12-10 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0032_merge_20241208_0326"),
        ("home", "0035_merge_20241208_1847"),
    ]

    operations = []
