# Generated by Django 4.2.14 on 2024-12-08 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_merge_20241123_1656'),
        ('home', '0035_merge_20241208_1847'),
    ]

    operations = [
    ]
