# Generated by Django 4.2.14 on 2024-12-09 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_examplemodel'),
        ('home', '0035_merge_20241208_1847'),
    ]

    operations = [
    ]
