# Generated by Django 4.2.14 on 2024-12-09 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_merge_0029_examplemodel_0035_merge_20241208_1847'),
        ('home', '0036_merge_20241208_2133'),
    ]

    operations = [
    ]
