# Generated by Django 4.2.14 on 2024-12-09 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_merge_20241207_1758'),
        ('home', '0037_merge_20241209_1328'),
    ]

    operations = [
    ]
