# Generated by Django 4.2.14 on 2024-12-09 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_blogpost_user_is_verified_and_more'),
        ('home', '0038_merge_20241209_1333'),
    ]

    operations = [
    ]
