# Generated by Django 4.2.14 on 2024-12-10 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0036_merge_20241210_1917"),
        ("home", "0038_merge_20241209_1333"),
    ]

    operations = []
