# Generated by Django 4.2.14 on 2024-12-10 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_merge_20241123_0027'),
        ('home', '0038_merge_20241209_1333'),
    ]

    operations = [
    ]
