# Generated by Django 4.2.14 on 2024-12-11 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_merge_20241118_2313'),
        ('home', '0028_contactsubmission_created_at'),
        ('home', '0030_user_last_activity'),
        ('home', '0039_merge_20241209_1707'),
        ('home', '0039_merge_20241210_2009'),
    ]

    operations = [
    ]
