# Generated by Django 4.2.14 on 2025-04-25 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_merge_20241210_2240'),
        ('home', '0040_merge_20241211_1419'),
    ]

    operations = [
    ]
