# Generated by Django 4.2.14 on 2025-04-26 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_merge_20250425_2316'),
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
    ]
