# Generated by Django 4.2.14 on 2025-04-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_userblogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='userblogpage',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
