# Generated by Django 4.2.14 on 2025-04-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberchallenge',
            name='time_limit',
            field=models.IntegerField(default=60, help_text='Time limit in seconds'),
        ),
    ]
