# Generated by Django 4.2.14 on 2025-05-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
