# Generated by Django 4.2.14 on 2025-04-25 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_merge_20250404_1619'),
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
    ]
