# Generated by Django 4.2.14 on 2025-04-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
