# Generated by Django 4.2.14 on 2025-04-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
