# Generated by Django 4.2.14 on 2025-05-05 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel'),
        ('home', '0042_apimodel_passkey'),
    ]

    operations = [
    ]
