# Generated by Django 4.2.14 on 2025-04-29 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_merge_0041_merge_20250425_2316_0042_apimodel_passkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
