# Generated by Django 4.2.14 on 2025-04-28 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_user_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='session_id',
            new_name='current_session_key',
        ),
    ]
