# Generated by Django 4.2.14 on 2025-04-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_cyberchallenge_time_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberchallenge',
            name='challenge_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fix_code', 'Fix the Code')], default='mcq', max_length=20),
        ),
        migrations.AddField(
            model_name='cyberchallenge',
            name='expected_output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cyberchallenge',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='choices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='time_limit',
            field=models.IntegerField(default=60),
        ),
    ]
