# Generated by Django 4.2.14 on 2025-05-02 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_apimodel_passkey'),
        ('home', '0043_user_current_session_key'),
    ]

    operations = [
    ]
