# Generated by Django 4.2.14 on 2025-04-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepuzzle',
            name='correct_answer',
            field=models.CharField(default='placeholder', max_length=255),
        ),
    ]
