# Generated by Django 4.2.14 on 2025-04-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_cyberchallenge_challenge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyberchallenge',
            name='sample_input',
            field=models.TextField(blank=True, null=True),
        ),
    ]
