# Generated by Django 4.2.14 on 2025-04-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_codepuzzle_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='codepuzzle',
            name='challenge_type',
            field=models.CharField(choices=[('write', 'Write'), ('fix', 'Fix')], default='write', max_length=10),
        ),
        migrations.AddField(
            model_name='codepuzzle',
            name='starter_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
