# Generated by Django 4.2.14 on 2025-04-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_cyberchallenge_sample_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberchallenge',
            name='category',
            field=models.CharField(choices=[('network', 'Network Security'), ('web', 'Web Application Security'), ('crypto', 'Cryptography'), ('general', 'General Knowledge'), ('python', 'Python'), ('javascript', 'JavaScript'), ('html_css', 'HTML & CSS'), ('web_security', 'Web Security'), ('reverse_engineering', 'Reverse Engineering'), ('forensics', 'Forensics'), ('binary_exploitation', 'Binary Exploitation'), ('linux', 'Linux'), ('algorithms', 'Algorithms'), ('data_structures', 'Data Structures'), ('databases', 'Databases'), ('regex', 'Regex'), ('secure_coding', 'Secure Coding'), ('logic_reasoning', 'Logic & Reasoning'), ('misc', 'Miscellaneous')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='challenge_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('fix_code', 'Fix the Code')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='explanation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='question',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='cyberchallenge',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
