# Generated by Django 4.2.14 on 2025-04-30 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_merge_20250322_0405'),
        ('home', '0043_merge_0042_apimodel_0042_apimodel_passkey'),
        ('home', '0043_user_current_session_key'),
        ('home', '0046_alter_cyberchallenge_category_and_more'),
    ]

    operations = [
    ]
