# Generated by Django 4.2.14 on 2025-04-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_user_current_session_key'),
        ('home', '0044_profile_github_profile_linkedin_profile_location_and_more'),
        ('home', '0046_alter_cyberchallenge_category_and_more'),
    ]

    operations = [
    ]
