# Generated by Django 4.2.14 on 2025-04-27 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_user_current_session_key'),
        ('home', '0046_alter_cyberchallenge_category_and_more'),
    ]

    operations = [
    ]
