# Generated by Django 4.2.7 on 2024-09-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_remove_user_is_admin_user_is_platform_leader_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_customer",
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_senior_developer",
            field=models.BooleanField(
                default=False, verbose_name="Is Platform Senior Developer"
            ),
        ),
    ]
