# Generated by Django 4.2.7 on 2024-09-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_user_is_customer_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_employee",
        ),
        migrations.AddField(
            model_name="user",
            name="is_platform_general_developer",
            field=models.BooleanField(
                default=False, verbose_name="Is Platform General Developer"
            ),
        ),
    ]
