# Generated by Django 4.2.7 on 2024-09-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_remove_user_is_employee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_external_user",
            field=models.BooleanField(default=False, verbose_name="Is External User"),
        ),
    ]
